---
- name: task to deploy
  gather_facts: false
  hosts: all
  become: yes
  vars:
    base_path: "/www/site"
    work_dir_path: "{{ base_path }}/app"
    env_path: "{{ base_path }}/venv"
    env_path_bin: "{{ env_path }}/bin"
  tasks:

  - name: pinpong
    ping:

  - name: update all package
    apt:
      name: "*"
      state: latest
      update_cache: yes
  
  - name: install packages list
    apt:
      name:
      - python3
      - python3-pip
      - python3-apt
      - python3-venv
      - nginx
      - git
      - tree
      
  - name: git clone app
    git:
      repo: https://github.com/ryabukha/site.git
      dest: "{{ base_path }}"
      force: yes
    register: git_clone_app

  - name: pip install flask
    pip:
      requirements: "{{ base_path }}/requirements.txt"
      virtualenv: "{{ env_path }}"
      virtualenv_command: 'python3 -m venv {{ env_path }}'

  - name: chown site work_dir_path
    file:
      path: "{{ work_dir_path }}"
      owner: www-data
      group: www-data
      mode: '0755'


  - name: create systemctl unit
    template:
      src: app_site.service.j2
      dest: /etc/systemd/system/app_site.service
    register: app_site_unit

  - name: create nginx config
    template:
      src: default.j2
      dest: /etc/nginx/sites-available/default
    register: nginx_config

  - name: just force systemd to re-execute itself (2.8 and above)
    systemd:
      daemon_reload: yes
    when: app_site_unit.changed

  - name: nginx is reloaded
    systemd:
      name: nginx
      state: reloaded
      enabled: yes
      masked: no
    when: nginx_config.changed

  - name: app_site is restarted
    systemd:
      name: app_site
      state: restarted
      enabled: yes
      masked: no
    when: app_site_unit.changed or git_clone_app.changed

  - name: nginx is started
    systemd:
      name: nginx
      state: started
      enabled: yes
      masked: no

  - name: flask is started
    systemd:
      name: app_site
      state: started
      enabled: yes
      masked: no

