"""empty message

Revision ID: 1d7ec64e3528
Revises: 01a2578ef5d5
Create Date: 2020-12-01 16:10:16.625061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d7ec64e3528'
down_revision = '01a2578ef5d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lastName', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lastName')
    # ### end Alembic commands ###
