"""empty message

Revision ID: 369ce852b408
Revises: 1d7ec64e3528
Create Date: 2020-12-01 16:10:39.944641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '369ce852b408'
down_revision = '1d7ec64e3528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
